addons: 
  chrome: stable
before_install: 
  - "sudo apt-get install -y chromium-chromedriver"
install: 
  - "pip install -r requirements.txt"
language: python
python: 
  - "3.7.3"
services: 
  - mysql
