language: python

python:
  - "3.7.3"      # current default Python on Travis CI
install:
  - pip install -r requirements.txt
services:
  - mysql
before_script:
  - wget https://chromedriver.storage.googleapis.com/88.0.4324.27/chromedriver_linux64.zip  
  - unzip chromedriver_linux64.zip -d /home/travis/venv
  - export CHROME_BIN=chromium-browser
  - cd todochat
script:
  - python manage.py test