language: python
addons:
	chrome: stable
before_install:
	- sudo apt-get install -y chromium-chromedriver
python:
  - "3.7.3"      # current default Python on Travis CI
install:
  - pip install -r requirements.txt
services:
  - mysql
script:
  - python todochat/manage.py test chat