# Generated by Django 3.0.7 on 2020-11-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200213_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.ImageField(default='default.png', upload_to='background_images'),
        ),
    ]
