# Generated by Django 3.0.7 on 2020-11-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.ImageField(default='default_background.jpg', upload_to='background_images'),
        ),
    ]
