# Generated by Django 3.0.7 on 2020-11-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201114_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userschat',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
