# Generated by Django 3.0.7 on 2020-12-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201207_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
