# Generated by Django 3.1.8 on 2021-04-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20201222_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userschat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usersmessage',
            name='id',
            field=models.CharField(default='error', max_length=20, primary_key=True, serialize=False),
        ),
    ]
