# Generated by Django 3.1.8 on 2021-04-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210410_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userschat',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
