# Generated by Django 3.1.8 on 2021-05-02 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0023_auto_20210416_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmessage',
            name='target_users',
            field=models.ManyToManyField(related_name='user_new_private_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
