# Generated by Django 3.0.7 on 2021-01-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210103_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_by',
            new_name='author',
        ),
    ]
