# Generated by Django 3.0.7 on 2021-01-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
