# Generated by Django 3.0.2 on 2020-01-29 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('color', models.CharField(default='#0277bc', max_length=20)),
                ('icon', models.CharField(default='House', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=300)),
                ('user_email', models.EmailField(max_length=50)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('dark_mode', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=300)),
                ('priority', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('color', models.CharField(default='#0277bc', max_length=20)),
                ('server_key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Server')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='users',
            field=models.ManyToManyField(to='app.User'),
        ),
    ]
