# Generated by Django 3.0.2 on 2020-02-06 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20200202_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.IntegerField(default=404, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default.png', upload_to='server_pics')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), related_name='server_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
