# Generated by Django 3.0.2 on 2020-02-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.CharField(default=models.CharField(max_length=20), max_length=18, primary_key=True, serialize=False),
        ),
    ]
