# Generated by Django 3.0.2 on 2020-02-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200206_2030'),
        ('app', '0005_auto_20200206_1259'),
    ]

    operations = [
    ]
