# Generated by Django 3.0.2 on 2020-02-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20200207_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.CharField(default=models.CharField(max_length=20), max_length=18, primary_key=True, serialize=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Server')),
            ],
        ),
    ]
