# Generated by Django 3.0.7 on 2020-12-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201017_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='server_pics'),
        ),
    ]
