# Generated by Django 3.0.7 on 2020-12-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
