# Generated by Django 3.0.7 on 2021-02-13 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInvitation',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_server_invitations', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_invitations', to='app.Server')),
            ],
        ),
    ]
