# Generated by Django 3.1.8 on 2021-04-30 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20210410_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='target_user',
            field=models.ManyToManyField(related_name='user_new_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
