# Generated by Django 3.1.8 on 2021-04-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_channelmessage_target_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelmessage',
            old_name='target_user',
            new_name='target_users',
        ),
    ]
