# Generated by Django 3.1.8 on 2021-05-02 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_serverinvitation'),
        ('chat', '0005_auto_20210430_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_private_messages', to='app.channel'),
        ),
    ]
